---
name: "pre-release"

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "v*"

jobs:
  gh_pre_release:
    runs-on: "ubuntu-latest"
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"
        with:
          lfs: true
          fetch-depth: 0

      - run: "zip khepri-industrial-equipment-$(git rev-parse --short HEAD).lcp *.json"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Pre-Release ${{ github.run_id }}"
          files: |
            *.lcp
        id: "automatic_releases"